### ISSUE TITLE
haploref.rb error

### ISSUE THREAD

**Issue by weishwu** [eturro/mmseq#30]
Anyone knows how to fix this error when running haploref.rb?

```
$ haploref.rb gencode.v29.transcripts.fa gencode.v29.annotation.gtf pos_99822 hap_99822
Reading FASTA file.../nfs/med-bfx-activeprojects/weishwu/common/mmseq-latest/bin/haploref.rb:79:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
        from /nfs/med-bfx-activeprojects/weishwu/common/mmseq-latest/bin/haploref.rb:75:in `open'
        from /nfs/med-bfx-activeprojects/weishwu/common/mmseq-latest/bin/haploref.rb:75:in `<main>'
```

**Comment by eturro** [comment]
No doubt the input is incorrectly formatted. I will add some more documentation on this.
